### PR TITLE
For consideration: Kokkos 3.5

### LINKED ISSUE #170: Update to Kokkos 3.5?
**Is your feature request related to a problem? Please describe.**
The EAGLES computation team is using [TChem](https://github.com/sandialabs/TChem) for aerosol and gas chemical kinetics. TChem makes pretty aggressive use of Kokkos, and recent updates use features exposed in Kokkos 3.5.

**Describe the solution you'd like**
We'd like to update EKAT to use Kokkos 3.5. We've tested that Kokkos 3.5 doesn't cause issues with EKAT the way we use it (in a branch of EKAT we're using within our own repository).

### PR DESCRIPTION
**Pull request by jeff-cohere**
This PR switches the `kokkos` submodule to track the 3.5.00 release tag. Everything seems to work within EKAT. We can use this branch to test things out in SCREAM, HAERO, etc.

No urgency at all on this one. It's just on my radar because HAERO's chemistry solver needs Kokkos 3.5. We can use this branch and rebase it against other merged PRs until it goes in.

Fixes #170

### CODE REVIEW

**Review by jgfouca — DISMISSED** [review]

**Comment by bartgol** [comment]
@jeff-cohere We need to use a version of kokkos that includes the commits in our fork. You could create a branch from 3.5, merge/cherry-pick the commits that are in the branch used by ekat/master, then push the branch to E3SM-Project/kokkos.

Note: the three commits we added are handling two issues we experienced:
- linking on Cori, where `-static` is used, but Kokkos kept trying to add `-ldl` to the link line
- linking on GPU when the main is in Fortran, where Kokkos was passing nvcc flags that gfortran would not like.

The second one _might_ be fixed in native Kokkos, for a recent enough CMake version (3.18). The first one, however, is still unhandled by kokkos (that I know of).

That said, we can always try to build homme (since it has F90 main, but anything else works) on GPU and Cori, and see how they behave.

**Comment by jeff-cohere** [comment]
Yup, I suspected something like that might be necessary, @bartgol . Thanks for laying things out. I guess I wanted to start simple and "rediscover" the things that we need. At least we know of those two potential issues.

Is this something we're interested in soonish? It might not be a huge effort, but I don't want to toss a wrench into SCREAM's v1 bugfix campaign.

**Comment by bartgol** [comment]
What does v3.5 give us? I don't have a ton of time right now, so unless it's a worthwhile addition, I would pass.

**Comment by jeff-cohere** [comment]
> What does v3.5 give us? 

You know, there was a recent talk they did at Sandia singing its virtues, but I didn't make it. And I am having trouble digging up specific info about the release. Maybe I'll just pick at this when I can for now.

**Comment by bartgol** [comment]
Well, I guess another way of saying it is "why does HAERO chem solver require v3.5"?

**Comment by jeff-cohere** [comment]
That's a fantastic question, and I'm embarrassed that I'm a bit too distant from that work to answer it myself. But I know who to ask about it. Let me see if I can get them on a Friday...

**Comment by bartgol** [comment]
No rush. I don't think we were gonna merge this today anyways. :)

**Review by bartgol — COMMENTED** [review]
Approving without approving. Once all correctness/performance tests downstream show no issues, we can real-approve/merge.

**Comment by jeff-cohere** [comment]
Hey @tcclevenger ,

Here's the PR that switches EKAT over to Kokkos 3.5. If you can set SCREAM's EKAT submodule to this branch and see how things shake out, I'd be super grateful!

Thanks for your help!

**Comment by tcclevenger** [comment]
Thanks @jeff-cohere. Testing now.

**Comment by jeff-cohere** [comment]
With @tcclevenger 's successful test of the Kokkos dev branch in SCREAM, is this PR ready to go? In it, the kokkos submodule is set to [this branch](https://github.com/E3SM-Project/kokkos/tree/jeff-cohere/v3.5.00) of E3SM's fork of Kokkos. Is that how we want to proceed?

**Comment by bartgol** [comment]
Yeah, I think it's fine

**Review by bartgol — APPROVED** [review]

**Pull request merged**
