### PR TITLE
Replacing --kokkos-num-devices with --kokkos-map-device-id-by=mpi_rank.

### PR DESCRIPTION
**Pull request by jeff-cohere**
This PR replaces a deprecated compiler flag as described in [SCREAM issue 2026](https://github.com/E3SM-Project/scream/issues/2026).

### CODE REVIEW

**Comment by bartgol** [comment]
I wonder if we should change this impl to use `InitializationSettings`, rather than mimicking cmd line argc/argv. Seems more readable. What do you think?

**Comment by jeff-cohere** [comment]
Sure, that makes sense. Let me put that together.

**Comment by jeff-cohere** [comment]
If we don't need to count available devices and we don't need to specify the number of threads, it looks like the new implementation of this function would be

```
// This function provides a simple and correct way to initialize Kokkos from
// any context with the correct settings.
void initialize_kokkos () {
  auto const settings = Kokkos::InitializationSettings()
    .set_num_threads(255)
    .map_device_id_by("mpi_rank")
    .set_disable_warnings(true);
  Kokkos::initialize(settings);
}
```

Does that look right to you, @bartgol ?

**Comment by bartgol** [comment]
> If we don't need to count available devices and we don't need to specify the number of threads, it looks like the new implementation of this function would be
> 
> ```
> // This function provides a simple and correct way to initialize Kokkos from
> // any context with the correct settings.
> void initialize_kokkos () {
>   auto const settings = Kokkos::InitializationSettings()
>     .map_device_id_by("mpi_rank")
>     .set_disable_warnings(true);
>   Kokkos::initialize(settings);
> }
> ```
> 
> Does that look right to you, @bartgol ?

Why not doing the device count? The code should not change from what's already in master, we simply need to add `.set_num_devices(nd)`, no?

**Comment by jeff-cohere** [comment]
True enough!

**Review by bartgol — DISMISSED** [review]

**Comment by ndkeen** [comment]
Fixes #2026

**Comment by ambrad** [comment]
We definitely want the device count. The comment was referring to the fact that it's not fatal not to get it. But it can decrease performance not to round-robin with the full number of devices.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
