### PR TITLE
Support HIP

### PR DESCRIPTION
**Pull request by ambrad**
* Make ekat.hpp the go-to header for Kokkos_Core.hpp (instead of including Kokkos_Core.hpp in various files) and EkatGpuSpace. This way, we can define Kokkos things that EKAT needs right after and be sure they are seen.
* Use EKAT_ENABLE_GPU in several spots instead of KOKKOS_ENABLE_CUDA.
* Use EkatGpuSpace in several spots instead of Kokkos::Cuda.
* Create some Kokkos::Experimental::HIP specializations.

### CODE REVIEW

**Comment by ambrad** [comment]
Tested on crusher with environment:
```
# Default env except for:
module load rocm
```
EKAT config:
```
rm -rf CMake*               
cmake \                         
    -D CMAKE_CXX_COMPILER=CC \    
    -D Kokkos_ENABLE_HIP=ON \           
    -D Kokkos_ARCH_VEGA90A=ON \    
    -D CMAKE_CXX_STANDARD=14 \    
    ~/repo/ekat
```
Didn't try to figure out MPI stuff, so all tests pass except
```
    8 - comm_np1 (Failed)                # and the other np values
   15 - debug_tools (Failed)                                                      
   25 - mpi_file_log_tests_np1 (Failed)  # and the other np values
   29 - console_only_log_np4 (Failed)
```

**Comment by ambrad** [comment]
A Summit case ran fine with this version of EKAT.

**Review by bartgol — APPROVED** [review]
Neat. Thanks!

**Comment by ambrad** [comment]
Do I need to do something other than add the label AT:RETEST to get this PR to go through the AT? Previous attempts a week ago were blocked by weaver being down. Thanks.

**Pull request merged**
